services:
  rproxy:
    build: 
      context: ./backend/reverse-proxy
      dockerfile: Dockerfile.dev
    image: reverse_proxy_dev:latest
    ports:
      - "5100:5100"
    restart: always
    depends_on:
      - auth
      - typesense
      - model
      - fetchers
    container_name: reverse_proxy

  auth:
    build: ./backend/auth-server
    image: auth_server:latest
    restart: always
    environment:
      - SECRET_KEY=supersecretkey
    container_name: auth_server

  fetchers:
    build: ./backend/data-fetchers
    image: fetch_server:latest
    restart: always
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/gcp/creds.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
      - GOOGLE_CLOUD_PROJECT=sentiment-test-417820
      - APININJAS_API_KEY=gOJYKW6v4X61Y7KBN1DDag==ZHXbpX663evhB9YE
    depends_on:
      - typesense
      - model
    container_name: fetch_server

  model:
    build: ./backend/sentiment-model
    image: model_server:latest
    restart: always
    container_name: model_server

  typesense:
    image: typesense/typesense:28.0
    volumes:
      - /tmp/data:/data
    command: --data-dir /data --api-key=Hu52dwsas2AdxdE
    restart: always
    container_name: typesense

  frontend:
    build: ./frontend
    image: frontend_wbs:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      - WBS_API_URL=http://reverse_proxy:5100
    container_name: frontend_wbs