services:
  rproxy:
    build: ./reverse-proxy
    image: reverse_proxy:latest
    ports:
      - "5100:5100"
    restart: always
    depends_on:
      - auth
      - typesense
      - model
      - fetchers
    container_name: reverse_proxy

  auth:
    build: ./auth-server
    image: auth_server:latest
    environment:
      - SECRET_KEY=supersecretkey
    container_name: auth_server

  fetchers:
    build: ./data-fetchers
    image: fetch_server:latest
    restart: always
    depends_on:
      - typesense
      - model
    container_name: fetch_server

  model:
    build: ./sentiment-model
    image: model_server:latest
    restart: always
    container_name: model_server

  typesense:
    image: typesense/typesense:28.0
    volumes:
      - /tmp/data:/data
    command: --data-dir /data --api-key=Hu52dwsas2AdxdE
    restart: always
    container_name: typesense