services:
  fetchers:
    build: .
    image: fetch_server:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5300:5300"
    restart: always
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/gcp/creds.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
      - GOOGLE_CLOUD_PROJECT=sentiment-test-417820
      - APININJAS_API_KEY=gOJYKW6v4X61Y7KBN1DDag==ZHXbpX663evhB9YE